name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: configure
      run: cd ./src
    - name: make
      run:  |
      sh kpxev2.sh
       name: Assemble artifact
        run: |
          rm -rf ./artifact/
          mkdir -p ./artifact/
          find ./src/bin/ -name "*kpxe*" | xargs -i mv -f {} ./artifact/
           - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: ipxe for legacybios 
          path: ./artifact/
   
