


name: ipxe-uefi

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
     
      - name: make uefi with EMBED
        run: |
          cd ..
          rm -rf ./uefi-EMBED/
          mkdir -p ./uefi-EMBED/
          sh loadefi.sh
          mv ./src/bin-x86_64-efi/*.efi ./uefi-EMBED/
                
      - name: make legacybios with EMBED
        run: |
          cd ..
          rm -rf ./legacybios-EMBED/
          mkdir -p ./legacybios-EMBED/
          sh kpxev2.sh
          mv ./src/bin/undionly.*pxe ./legacybios-EMBED/ 
          cd ..   
      
      - name: upload release with EMBED
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Latest"
          prerelease: false
          title: "Development Build legacybios and uefi [ipxe 的启动文件已嵌入脚本]"
          files: |
            ./legacybios-EMBED/*.*
            ./uefi-EMBED/*.*
