


name: ipxe-uefi

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master
     
      - name: make ipxe with EMBED
        run: |
          rm -rf ./uefi-EMBED/
          mkdir -p ./uefi-EMBED/
          sh loadefi.sh
          ls ./src/bin
          mv ./src/bin-x86_64-efi/*.efi ./uefi-EMBED/
          rm -rf ./legacybios-EMBED/
          mkdir -p ./legacybios-EMBED/
          sh kpxev2.sh
          mv ./src/bin/undionly.kkpxe ./legacybios-EMBED/    
          mv ./src/bin/undionly.kpxe ./legacybios-EMBED/ 
          mv ./src/bin/undionly.kkkpxe ./legacybios-EMBED/ 
          mv ./src/bin/undionly.kpxe ./legacybios-EMBED/   
       
      - name: Upload ipxe with EMBED
        uses: actions/upload-artifact@master
        with:
          name: ipxe for legacy and uefi with EMBED
          path: |
            ./uefi-EMBED/
            ./legacybios-EMBED/
 
      - name: upload release with EMBED
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Latest"
          prerelease: false
          title: "Development Build legacybios and uefi [ipxe 的启动文件已嵌入脚本]"
          files: |
            ./legacybios-EMBED/*.*
            ./uefi-EMBED/*.*
