


name: ipxe-uefi

on:
  push:
    branches: 
      - master
  # schedule:
  #   - cron: 0 20 * * *
  # release:
  #   types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: make
        run: |
          sh loadefi.sh   
          sh kpxev2.sh  
      
      - name: ipxe for all
        run: |
          rm -rf ./uefi/
          rm -rf ./legacybios/
          mkdir -p ./uefi/
          mkdir -p ./legacybios/
          find ../src/bin/ -name "*efi*" | xargs -i mv -f {} ./uefi/
          find ../src/bin/ -name "*pxe*" | xargs -i mv -f {} ./legacybios/
          cp ./src/bin/*.efi ./uefi/  
          cp ./src/bin/undionly.kkpxe ./legacybios/    
          cp ./src/bin/undionly.kpxe ./legacybios/ 
          cp ./src/bin/undionly.kkkpxe ./legacybios/ 
          cp ./src/bin/undionly.kpxe ./legacybios/   
       
      - name: Upload ipxe
        uses: actions/upload-artifact@master
        with:
          name: ipxe for legacy and uefi
          path: |
            ./uefi/
            ./legacybios/
 
      - name: upload release  
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "Latest"
          prerelease: false
          title: "Development Build legacybios and uefi [ipxe 的启动文件]"
          files: |
            ./legacybios/*.*
            ./uefi/*.*
